version: '3'
services:

  web:
    image: ansible/awx_web:latest
    depends_on:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        # max_attempts: 3
        window: 60s
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
      SECRET_KEY: awxsecret
      DATABASE_NAME: awx
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      AWX_ADMIN_USER: admin
      AWX_ADMIN_PASSWORD: password

  task:
    image: ansible/awx_task:latest
    depends_on:
      - rabbitmq
      - memcached
      - web
      - postgres
    hostname: awx
    user: root
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        # max_attempts: 3
        window: 60s
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
      SECRET_KEY: awxsecret
      DATABASE_NAME: awx
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      AWX_ADMIN_USER: admin
      AWX_ADMIN_PASSWORD: password

  rabbitmq:
    image: rabbitmq:3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        # max_attempts: 3
        window: 60s
    environment:
      RABBITMQ_DEFAULT_VHOST: awx

  memcached:
    image: memcached:alpine
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        # max_attempts: 3
        window: 60s

  postgres:
    image: postgres:9.6
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        # max_attempts: 3
        window: 60s
    volumes:
      - /data/awx:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
