version: '3'

services:

  # https://github.com/jenkinsci/docker/blob/master/README.md
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - '8080:8080'
      - '50000:50000'
    # environment:
      # JAVA_OPTS: "-Djava.awt.headless=true"
    volumes:
      - /data/jenkins:/var/jenkins_home
