---
# tasks file for ark

# ark will run with user:group 1000:1000 in the docker container itself,
# so I'm using that user:group for the volume as well.
- name: Create directories for docker volumes
  become: true
  file:
    path: "{{ ark_dir }}"
    state: directory
    owner: 1000
    group: 1000
    mode: 0755
  tags:
    - ark

- name: Generate "{{ item }}"
  template:
    src: "{{ item }}.j2"
    dest: "{{ ark_dir }}/{{ item }}"
    mode: 0644
  with_items:
    - arkmanager.cfg
    - GameUserSettings.ini
    - Game.ini
    - crontab
  tags:
    - ark
