---

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - nmap # why?
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: add docker ce repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker ce repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
    filename: docker
    update_cache: true

- name: install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: true
